sudo: false

language: python

matrix:
  include:
    - python: '3.6'
      env: TESTENV=lint
    - python: '3.6'
      env: TESTENV=py36
    - python: '3.7-dev'
      env: TESTENV=py37

before_script:
  - pip install 'flake8>=3.6.0,<3.7.0' pydocstyle pytest
  - if [ "$TESTENV" != "lint" ]; then pip install 'errbot<6.0'; fi

script:
  - if [ "$TESTENV" = "lint" ];  then flake8; fi
  - if [ "$TESTENV" = "lint" ];  then pydocstyle; fi
  - if [ "$TESTENV" != "lint" ]; then pytest tests/; fi
